#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Wnx\PhotoCrop\PhotoCropCommand;

$application = new Application();
$application->add(new PhotoCropCommand());

$application->run();
